- name: install nginx
  yum:
    name: nginx
    state: present

- name: changing nginx configurations
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: copy front end files
  copy:
    src: nahmReads
    dest: /usr/share/nginx/html
    
- name: start nginx
  service:
    name: nginx
    state: restarted